# Cascading for the Impatient

The Impatient series is a set of tutorials to get you started with Cascading
2.2.

This set of progressive coding examples starts with a simple file copy and
builds up to a MapReduce implementation of the TF-IDF algorithm


link:impatient1.html[Part 1]
----------------------------
- Implements simplest Cascading app possible
- Copies each TSV line from source tap to sink tap
- Roughly, in about a dozen lines of code
- Physical plan: 1 Mapper


link:impatient2.html[Part 2]
----------------------------
- Implements a simple example of WordCount
- Uses a regex to split the input text lines into a token stream
- Generates a DOT file, to show the Cascading flow graphically
- Physical plan: 1 Mapper, 1 Reducer


link:impatient3.html[Part 3]
----------------------------
- Uses a custom Function to scrub the token stream
- Discusses when to use standard Operations vs. creating custom ones
- Physical plan: 1 Mapper, 1 Reducer

link:impatient4.html[Part 4]
----------------------------
- Shows how to use a HashJoin on two pipes
- Filters a list of stop words out of the token stream
- Physical plan: 1 Mapper, 1 Reducer

link:impatient5.html[Part 5]
----------------------------
- Calculates TF-IDF using an ExpressionFunction
- Shows how to use a CountBy, SumBy, and a CoGroup
- Physical plan: 10 Mappers, 8 Reducers

link:impatient6.html[Part 6]
----------------------------
- Includes unit tests in the build
- Shows how to use other TDD features: checkpoints, assertions, traps, debug
- Physical plan: 11 Mappers, 8 Reducers



